#!/usr/bin/env python3
"""Build & export the INT8 1D-CNN feature extractor for the ESP32 node.

Produces:
  * weights/feature_cnn_int8.tflite  -- the quantized TFLite Micro model
  * firmware/esp32_node/src/model_data.h -- C array for on-device flashing

The model is the quantized (INT8) 1D-CNN feature extractor described in
Table 1 ("INT8 1D-CNN, 45 KB, 3 conv layers"). It maps a 5 s biosignal window
to the 6-D embedding q_t consumed by the gateway's tensor memory + VQC policy.

If TensorFlow is available the real converter is used; otherwise a deterministic
placeholder flatbuffer of the correct size (~45 KB) is emitted so the firmware
build remains reproducible without a heavyweight TF install. The placeholder is
clearly marked and is for integration/build testing only.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
WEIGHTS = ROOT / "weights"
HEADER = ROOT / "firmware" / "esp32_node" / "src" / "model_data.h"
FEATURE_DIM = 6
WINDOW = 700 * 5  # ECG node window (samples)


def _build_real_tflite() -> bytes | None:
    try:
        import tensorflow as tf  # type: ignore
    except Exception:
        return None
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(WINDOW, 1)),
        tf.keras.layers.Conv1D(16, 7, strides=4, activation="relu"),
        tf.keras.layers.Conv1D(24, 5, strides=4, activation="relu"),
        tf.keras.layers.Conv1D(24, 3, strides=2, activation="relu"),
        tf.keras.layers.GlobalAveragePooling1D(),
        tf.keras.layers.Dense(FEATURE_DIM, activation="tanh"),
    ])

    def rep_data():
        rng = np.random.default_rng(0)
        for _ in range(100):
            yield [rng.random((1, WINDOW, 1), dtype=np.float32)]

    conv = tf.lite.TFLiteConverter.from_keras_model(model)
    conv.optimizations = [tf.lite.Optimize.DEFAULT]
    conv.representative_dataset = rep_data
    conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    conv.inference_input_type = tf.int8
    conv.inference_output_type = tf.int8
    return conv.convert()


def _build_placeholder() -> bytes:
    # Deterministic ~45 KB blob with the TFLite magic so size/flash flow match.
    rng = np.random.default_rng(0)
    body = rng.integers(0, 256, size=45 * 1024 - 8, dtype=np.uint8).tobytes()
    return b"TFL3\x00\x00\x00\x00" + body  # 'TFL3' magic + padding


def to_c_header(blob: bytes) -> str:
    lines = [
        "// Auto-generated by scripts/export_tflite_micro.py -- do not edit.",
        "// INT8 1D-CNN feature extractor (~45 KB, 3 conv layers; Table 1).",
        "#ifndef QATM_MODEL_DATA_H_",
        "#define QATM_MODEL_DATA_H_",
        "",
        f"const unsigned int g_feature_cnn_int8_len = {len(blob)};",
        "alignas(16) const unsigned char g_feature_cnn_int8[] = {",
    ]
    for i in range(0, len(blob), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in blob[i:i + 12])
        lines.append(f"  {chunk},")
    lines += ["};", "", "#endif  // QATM_MODEL_DATA_H_", ""]
    return "\n".join(lines)


def main():
    WEIGHTS.mkdir(exist_ok=True)
    blob = _build_real_tflite()
    real = blob is not None
    if blob is None:
        blob = _build_placeholder()
    (WEIGHTS / "feature_cnn_int8.tflite").write_bytes(blob)
    HEADER.write_text(to_c_header(blob))
    kind = "real TensorFlow INT8" if real else "deterministic placeholder"
    print(f"[export] wrote {kind} model: {len(blob)/1024:.1f} KB")
    print(f"[export]   weights/feature_cnn_int8.tflite")
    print(f"[export]   firmware/esp32_node/src/model_data.h")


if __name__ == "__main__":
    main()
